In [1]:
import pandas as pd
from tqdm import tqdm
import os

# GSE37302

In [2]:
gse37302 = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse37302/GSE37302.top.table.tsv", sep="\t")
gse37302 = gse37302[gse37302['adj.P.Val'] <= 0.05]
gse37302_genes = list(set(gse37302['ORF'].values.tolist()))
gse37302_genes =sorted([i for i in gse37302_genes if not "nan" in str(i).lower()])
with open('gse37302_genes.txt','w') as handle:
    for gen in gse37302_genes:
        handle.write(gen + "\n")

# GSE39683

In [3]:
gse39683_genecounts = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse39683/GSE39683.top.table.tsv", sep="\t")
gse39683_genecounts = gse39683_genecounts[gse39683_genecounts["adj.P.Val"] <= 0.05]
gene_probemapping = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse39683/gProfiler_hsapiens_28-04-2023_20-53-58.csv")
gene_probemapping.columns = ["ID"] + gene_probemapping.columns.tolist()[1:]
gene_probemapping["ID"] = [i.lower() for i in gene_probemapping["ID"].values.tolist()]
gse39683_genecounts1 = gse39683_genecounts.merge(gene_probemapping, on=["ID"])
gse39683_genecounts1_genes = sorted(list(set([i for i in gse39683_genecounts1["name"] if not "none" in str(i).lower()])))
with open("gse39683_genes.txt", "w") as handle:
    for gen in gse39683_genecounts1_genes:
        handle.write(gen + "\n")

gse39683_genecounts1.head()

,ID,adj.P.Val,P.Value,t,B,logFC,SPOT_ID,Description,converted_alias,name,description,namespace
0,933_at,1.870000e-45,9.510000e-50,-47.945383,99.964830,-7.208842,933,CD22 molecule,None,None,None,NaN
1,2841_at,5.750000e-44,5.840000e-48,-44.697743,96.414938,-6.568676,2841,G protein-coupled receptor 18,None,None,None,NaN
2,941_at,2.670000e-37,4.070000e-41,-34.073867,82.246194,-5.895277,941,CD80 molecule,AC233723,PSMB6,proteasome 20S subunit beta 6 [Source:HGNC Sym...,"AFFY_HC_G110,AFFY_HG_U95A,AFFY_HG_U95AV2"
3,941_at,2.670000e-37,4.070000e-41,-34.073867,82.246194,-5.895277,941,CD80 molecule,AK311768,PSMB6,proteasome 20S subunit beta 6 [Source:HGNC Sym...,"AFFY_HC_G110,AFFY_HG_U95A,AFFY_HG_U95AV2"
4,941_at,2.670000e-37,4.070000e-41,-34.073867,82.246194,-5.895277,941,CD80 molecule,BC000835,PSMB6,proteasome 20S subunit beta 6 [Source:HGNC Sym...,"AFFY_HC_G110,AFFY_HG_U95A,AFFY_HG_U95AV2"

# GSE46053

In [4]:
gse46053 = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse46053/GSE46053.top.table.tsv", sep="\t")
gse46053 = gse46053[gse46053["adj.P.Val"] <= 0.05]
gse46053_genes = sorted(list(set([i for i in gse46053["ORF"].values.tolist() if not "none" in i.lower()])))
with open("gse46053_genes.txt", "w") as handle:
    for gen in gse46053_genes:
        handle.write(gen + "\n")

# GSE46609

In [5]:
gse46609 = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse46609/GSE46609.top.table.tsv", sep="\t")
gse46609 = gse46609[gse46609["adj.P.Val"] <= 0.05]
gse46609_genes = sorted(list(set([i for i in gse46609["Gene.symbol"] if not "nan" in str(i).lower()])))
gse46609_genes

['BAG3', 'DNAJB1', 'HSPA1B', 'LCMT2']

# GSE72213

In [6]:
gse72213 = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse72213/genes.tsv", sep="\t")
gene_probemapping = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse72213/gProfiler_hsapiens_28-04-2023_15-15-38.csv")
gene_probemapping.columns = ["ID"] + gene_probemapping.columns.tolist()[1:]
gse72213 = gse72213.merge(gene_probemapping, on=["ID"])
gse72213_genes = sorted(list(set(gse72213["name"].values.tolist())))
with open("gse72213_genes.txt", "w") as handle:
    for gen in gse72213_genes:
        handle.write(gen + "\n")
gse72213.head()

,ID,log2(fold change),-log10(Pvalue),converted_alias,name,description,namespace
0,A_19_P00315529,-2.904,3.245,ENSG00000237943,PRKCQ-AS1,PRKCQ antisense RNA 1 [Source:HGNC Symbol;Acc:...,"AGILENT_SUREPRINT_G3_GE_8X60K,AGILENT_SUREPRIN..."
1,A_19_P00315900,-2.383,3.029,ENSG00000234323,LINC01505,long intergenic non-protein coding RNA 1505 [S...,"AGILENT_GPL19072,AGILENT_SUREPRINT_G3_GE_8X60K..."
2,A_19_P00317054,-3.146,3.748,ENSG00000228956,SATB1-AS1,SATB1 antisense RNA 1 [Source:HGNC Symbol;Acc:...,"AGILENT_GPL19072,AGILENT_SUREPRINT_G3_GE_8X60K..."
3,A_19_P00317277,-3.194,3.274,ENSG00000281162,LINC01127,long intergenic non-protein coding RNA 1127 [S...,"AGILENT_GPL19072,AGILENT_SUREPRINT_G3_GE_8X60K..."
4,A_19_P00317639,-3.517,4.274,ENSG00000245164,LINC00861,long intergenic non-protein coding RNA 861 [So...,"AGILENT_SUREPRINT_G3_GE_8X60K,AGILENT_SUREPRIN..."

# GSE78884

In [7]:
gse78884 = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse78884/GSE78884.top.table.tsv", sep="\t")
gse78884 = gse78884[gse78884["adj.P.Val"] <= 0.05]
gse78884_genes = sorted(list(set(gse78884["GENE_NAME"].values.tolist())))
with open("gse78884_genes.txt", "w") as handle:
    for gen in gse78884_genes:
        handle.write(gen + "\n")

gse78884.head()

,ID,adj.P.Val,P.Value,t,B,logFC,GB_LIST,GENE_NAME,SPOT_ID
0,467,0.000382,3.080000e-07,8.337315,6.9794,2.827543,NM_017957,EPN3,NaN
1,404,0.000382,5.940000e-07,-7.930107,6.3692,-1.999343,NM_021235,EPS15L1,NaN
2,60,0.001135,2.640000e-06,-7.050291,4.9663,-2.089800,"NM_005345, NM_005346",HSPA1A-HSPA1B,NaN
3,673,0.001750,7.150000e-06,-6.495496,4.0208,-2.664657,NM_016494,LOC51255,NaN
4,6,0.001750,8.120000e-06,6.426159,3.8993,1.346543,NM_178014,TUBB_HUMAN,NaN

# GSE89182

In [8]:
gse89182 = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse89182/GSE89812.top.table.tsv", sep="\t")
gse89182 = gse89182[gse89182["adj.P.Val"] <= 0.05]
gse89182_genes = sorted(list(set([i for i in gse89182["Gene.symbol"].values.tolist() if not "nan" in str(i).lower()])))
with open("gse89182_genes.txt", "w") as handle:
    for gen in gse89182_genes:
        handle.write(gen + "\n")

gse89182.head()

,ID,adj.P.Val,P.Value,t,B,logFC,GI,Gene.symbol,Gene.title
0,ILMN_1860722,1.730000e-07,9.100000e-12,25.584537,16.441742,6.070218,23371365.0,NaN,NaN
1,ILMN_1753342,1.740000e-07,1.830000e-11,24.099697,15.927773,4.138701,654823989.0,SAT1,spermidine/spermine N1-acetyltransferase 1
2,ILMN_1793990,3.870000e-07,6.090000e-11,21.736955,15.000011,3.500998,33946335.0,ID2,"inhibitor of DNA binding 2, HLH protein"
3,ILMN_2266948,1.540000e-06,3.240000e-10,18.815480,13.626231,2.717093,117168274.0,SLC38A1,solute carrier family 38 member 1
4,ILMN_1660357,2.180000e-06,6.300000e-10,17.759279,13.055178,2.852408,NaN,NaN,NaN

# GSE125363

In [9]:
gse125363 = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse125363/GSE125363.top.table.tsv", sep="\t")
gse125363 = gse125363[gse125363["adj.P.Val"] <= 0.05]
gene_mirmapping = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse125363/mir2gene.csv")
gene_mirmapping.columns = ["miRNA_ID"] + gene_mirmapping.columns.tolist()[1:]
gene_mirmapping["miRNA_ID"] = [i.lower()[:-3] for i in gene_mirmapping["miRNA_ID"].values.tolist()]
gse125363["miRNA_ID"] = [str(i).lower()[:-3] for i in gse125363["miRNA_ID"].values.tolist()]
gse125363 = gse125363.merge(gene_mirmapping, on=["miRNA_ID"])
gse125363_genes = sorted(list(set(gse125363["Target"].values.tolist())))
with open("gse125363_genes.txt", "w") as handle:
    for gen in gse125363_genes:
        handle.write(gen + "\n")

gse125363.head()

,ID,adj.P.Val,P.Value,t,B,logFC,miRNA_ID,SPOT_ID,Accession,Target,TargetID,Experiment,Literature,Tissue
0,55873,3.980000e-09,6.380000e-14,-10.325731,20.295798,-1.955485,hsa-mir-4,NaN,MIMAT0001541,ADAM10,102.0,Luciferase reporter assay//qRT-PCR//Western blot,27398144,Unspecified
1,55873,3.980000e-09,6.380000e-14,-10.325731,20.295798,-1.955485,hsa-mir-4,NaN,MIMAT0001541,ARHGAP1,392.0,PAR-CLIP,23592263|21572407|20371350|27292025,Unspecified
2,55873,3.980000e-09,6.380000e-14,-10.325731,20.295798,-1.955485,hsa-mir-4,NaN,MIMAT0001541,ATP6V1E1,529.0,PAR-CLIP,27292025,Unspecified
3,55873,3.980000e-09,6.380000e-14,-10.325731,20.295798,-1.955485,hsa-mir-4,NaN,MIMAT0001541,CCND1,595.0,Flow//Immunoblot//Luciferase reporter assay//q...,20948989|24248414,Unspecified
4,55873,3.980000e-09,6.380000e-14,-10.325731,20.295798,-1.955485,hsa-mir-4,NaN,MIMAT0001541,BCL2,596.0,ChIP-seq//Flow//Luciferase reporter assay//qRT...,21569010|24248414|24260067|24960059|27351886,Unspecified

# GSE125364 [Removed]

In [10]:
# gse125364 = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse125364/GSE125364.top.table.tsv", sep="\t")
# gse125364 = gse125364[gse125364["adj.P.Val"] <= 0.05]
# gene_probemapping = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse125364/gProfiler_hsapiens_28-04-2023_17-30-55.csv")
# gene_probemapping.columns = ["SPOT_ID"] + gene_probemapping.columns.tolist()[1:]
# gse125364 = gse125364.merge(gene_probemapping, on=["SPOT_ID"])
# gse125364_genes = sorted(list(set(gse125364["name"].values.tolist())))
# with open("gse125364_genes.txt", "w") as handle:
#     for gen in gse125364_genes:
#         handle.write(gen + "\n")

# gse125364.head()

# GSE137369

In [10]:
gse137369_genes = open("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/gse137369_genes.txt").read().split("\n")[:-1]

# GSE 17306

In [11]:
gse17306 = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse17306/GSE17306.top.table.tsv", sep="\t")
gse17306 = gse17306[gse17306["adj.P.Val"] <= 0.05]
gene_mirmapping = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse17306/mir2gene.csv")
gene_mirmapping.columns = ["miRNA_ID"] + gene_mirmapping.columns.tolist()[1:]
gene_mirmapping["miRNA_ID"] = [i.lower()[:-3] for i in gene_mirmapping["miRNA_ID"].values.tolist()]
gse17306["miRNA_ID"] = [str(i).lower()[:-3] for i in gse17306["miRNA_ID"].values.tolist()]
gse17306 = gse17306.merge(gene_mirmapping, on=["miRNA_ID"])
gse17306_genes = sorted(list(set(gse17306["Target"].values.tolist())))
with open("gse17306_genes.txt", "w") as handle:
    for gen in gse17306_genes:
        handle.write(gen + "\n")

gse17306.head()

,ID,adj.P.Val,P.Value,t,B,logFC,ORGANISM,miRNA_ID,SPOT_ID,Accession,Target,TargetID,Experiment,Literature,Tissue
0,hsa-miR-663,0.000307,8.300000e-07,5.58432,5.6561,4.576052,Homo sapiens,hsa-mir-,NaN,MIMAT0000104,ABL2,27.0,PAR-CLIP,24398324|23446348|21572407|20371350,Unspecified
1,hsa-miR-663,0.000307,8.300000e-07,5.58432,5.6561,4.576052,Homo sapiens,hsa-mir-,NaN,MIMAT0000104,ACVR2B,93.0,PAR-CLIP,21572407,Unspecified
2,hsa-miR-663,0.000307,8.300000e-07,5.58432,5.6561,4.576052,Homo sapiens,hsa-mir-,NaN,MIMAT0000104,ADD2,119.0,CLASH,23622248,Unspecified
3,hsa-miR-663,0.000307,8.300000e-07,5.58432,5.6561,4.576052,Homo sapiens,hsa-mir-,NaN,MIMAT0000104,ADORA3,140.0,HITS-CLIP,19536157,Unspecified
4,hsa-miR-663,0.000307,8.300000e-07,5.58432,5.6561,4.576052,Homo sapiens,hsa-mir-,NaN,MIMAT0000104,ALDH3B1,221.0,PAR-CLIP,23592263,Unspecified

# GSE16558

In [12]:
gse16558 = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse16558/GSE16558.top.table.tsv", sep="\t")
gse16558 = gse16558[gse16558["adj.P.Val"] <= 0.05]
gse16558_gene = sorted(list(set([i for i in gse16558["Gene.symbol"].values.tolist() if not "nan" in str(i).lower()])))
with open("gse16558_genes.txt", "w") as handle:
    for gen in gse16558_gene:
        handle.write(gen + "\n")

# GSE17498

In [13]:
gse17498 = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse17498/GSE17498.top.table.tsv", sep="\t")
gse17498 = gse17498[gse17498["adj.P.Val"] <= 0.05]
gene_mirmapping = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse17498/mir2gene.csv")
gene_mirmapping.columns = ["miRNA_ID"] + gene_mirmapping.columns.tolist()[1:]
gene_mirmapping["miRNA_ID"] = [i.lower()[:-3] for i in gene_mirmapping["miRNA_ID"].values.tolist()]
gse17498["miRNA_ID"] = [i.lower()[:-3] for i in gse17498["miRNA_ID"].values.tolist()]
gse17498 = gse17498.merge(gene_mirmapping, on=["miRNA_ID"])
gse17498_genes = sorted(list(set(gse17498["Target"].values.tolist())))
with open("gse17498_genes.txt", "w") as handle:
    for gen in gse17498_genes:
        handle.write(gen + "\n")

gse17498.head()

,ID,adj.P.Val,P.Value,t,B,logFC,ORGANISM,miRNA_ID,SPOT_ID,SPOT_ID.1,Accession,Target,TargetID,Experiment,Literature,Tissue
0,hsa-miR-363,2.360000e-13,3.260000e-16,-12.670357,26.726,-3.319857,Homo sapiens,hsa-mir-,NaN,NaN,MIMAT0000104,ABL2,27.0,PAR-CLIP,24398324|23446348|21572407|20371350,Unspecified
1,hsa-miR-363,2.360000e-13,3.260000e-16,-12.670357,26.726,-3.319857,Homo sapiens,hsa-mir-,NaN,NaN,MIMAT0000104,ACVR2B,93.0,PAR-CLIP,21572407,Unspecified
2,hsa-miR-363,2.360000e-13,3.260000e-16,-12.670357,26.726,-3.319857,Homo sapiens,hsa-mir-,NaN,NaN,MIMAT0000104,ADD2,119.0,CLASH,23622248,Unspecified
3,hsa-miR-363,2.360000e-13,3.260000e-16,-12.670357,26.726,-3.319857,Homo sapiens,hsa-mir-,NaN,NaN,MIMAT0000104,ADORA3,140.0,HITS-CLIP,19536157,Unspecified
4,hsa-miR-363,2.360000e-13,3.260000e-16,-12.670357,26.726,-3.319857,Homo sapiens,hsa-mir-,NaN,NaN,MIMAT0000104,ALDH3B1,221.0,PAR-CLIP,23592263,Unspecified

# GSE146649 [NOT PUBLISHED]

In [14]:
# df = pd.read_csv("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse146649/GSE146649.top.table.tsv", sep="\t")
# genelist = []
# for idx in tqdm(range(df.shape[0])):
#     if not '//' in str(df.iloc[idx, -2]):
#         genelist.append(df.iloc[idx, -2])    
#     else:
#         glist = df.iloc[idx, -2].split("//")
#         for i in glist:
#             genelist.append(i)
# genelist = sorted([i[1:] for i in genelist if not str(i)[0] == "//" and not "nan" in str(i).lower()])
# with open("gse146649_genes.txt", "w") as handle:
#     for gen in genelist:
#         handle.write(gen + "\n")

# GSE149833

In [15]:
df = pd.read_excel('/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse149833/GSE149833.top.table.xlsx')
gse149833_genes = sorted([i.split("//")[1].replace(' ','') for i in df["gene_assignment"].values.tolist() if not "nan" in str(i).lower() and not "--" in i])
with open("gse149833_genes.txt", "w") as handle:
    for gen in gse149833_genes:
        handle.write(gen + "\n")
df.head()

,ID,adj.P.Val,P.Value,t,logFC,gene_assignment,SPOT_ID
0,TC1200010158.hg.1,0.00274,1.970000e-08,-8.031878,-2.900,NM_004985 // KRAS // Kirsten rat sarcoma viral...,NM_004985 // RefSeq
1,TC0500010576.hg.1,0.01032,1.490000e-07,7.173916,0.778,---,T281415 // miTranscriptome
2,TC1700008969.hg.1,0.02887,6.240000e-07,6.587241,0.695,"uc060knl.1 // RNU6-97P // RNA, U6 small nuclea...",uc060knl.1 // UCSC Genes
3,TC0600009004.hg.1,0.05402,1.570000e-06,6.218865,0.501,"uc063qka.1 // RNU6-1299P // RNA, U6 small nucl...",uc063qka.1 // UCSC Genes
4,TC0600012849.hg.1,0.05402,2.400000e-06,6.049707,0.640,"uc063qqg.1 // RNU6-906P // RNA, U6 small nucle...",uc063qqg.1 // UCSC Genes

# GSE167042

In [16]:
df = pd.read_excel("/home/vivek/jupyter_notebooks/bio_dgi_extension/additional_database_validation/additional_database_validation/gse167042/GSE167042.top.table.xlsx")
gse167042_genes = sorted([i.split("//")[1].replace(' ','') for i in df["gene_assignment"].values.tolist() if not "nan" in str(i).lower() and not "--" in i])
with open("gse167042_genes.txt", "w") as handle:
    for gen in gse167042_genes:
        handle.write(gen + "\n")
df.head()

,ID,adj.P.Val,P.Value,t,B,logFC,probeset_id,seqname,strand,start,total_probes,gene_assignment
0,TC0500007076.hg.1,0.0323,3.810000e-07,18.7,5.169442,3.56,TC0500007076.hg.1,chr5,+,32653048,10.0,---
1,TC1700007186.hg.1,0.0323,4.650000e-07,18.2,5.090728,3.60,TC1700007186.hg.1,chr17,+,19603797,10.0,ENST00000417560 // MTND2P12 // mitochondrially...
2,TC0500007077.hg.1,0.0346,7.480000e-07,17.0,4.891762,3.18,TC0500007077.hg.1,chr5,+,32689070,10.0,NM_000908 // NPR3 // natriuretic peptide recep...
3,TC1700007184.hg.1,0.0489,1.410000e-06,15.4,4.597955,3.38,TC1700007184.hg.1,chr17,+,19602259,10.0,ENST00000427400 // MTND1P14 // mitochondrially...
4,TC1000008894.hg.1,0.0530,2.040000e-06,14.6,4.411300,3.45,TC1000008894.hg.1,chr10,+,110545655,10.0,---

# Consensus or Union of all dstasets

In [17]:
common_genes = list(set(gse37302_genes) & set(gse39683_genecounts1_genes) & set(gse17306_genes) & set(gse16558_gene) & set(gse72213_genes) & set(gse17498_genes) & set(gse89182_genes) & set(gse125363_genes) & set(gse137369_genes) & set(gse167042_genes) & set(gse149833_genes))
common_genes

[]

In [18]:
all_genes = list(set(gse37302_genes + gse39683_genecounts1_genes + gse17306_genes + gse16558_gene + gse72213_genes + gse17498_genes + gse89182_genes + gse125363_genes + gse137369_genes + gse167042_genes + gse149833_genes))
top500_genes = open("/home/vivek/jupyter_notebooks/bio_dgi_extension/ppi_string_merged/new_model4/best_performing_model/top_500_genes.txt").read().split("\n")
top100_genes = top500_genes[:100]
top250_genes = top500_genes[:250]
genepanel77 = open("/home/vivek/jupyter_notebooks/bio_dgi_extension/farcastbio/77genelist.txt").read().split("\n")
genepanel34 = open("/home/vivek/jupyter_notebooks/bio_dgi_extension/farcastbio/genelist77_mm_mgus.txt").read().split("\n")[:-1]

In [20]:
gene798_rank =  pd.read_excel("/home/vivek/jupyter_notebooks/bio_dgi_extension/ppi_string_merged/new_model4/best_performing_model/gene798_ranking.xlsx", index_col=0)
df_dataset_counts = pd.DataFrame()
gse37302_col, gse39683_genecounts1_col, gse17306_col, gse16558_col, gse72213_col, gse17498_col, gse89182_col, gse125363_col, gse167042_col, gse149833_col, gse137369_col = [], [],[],[],[],[],[],[],[],[], []
generank = []
genelist = gene798_rank.index.tolist()
for gen in tqdm(genelist):
    generank.append(genelist.index(gen)+1)
    if gen in gse37302_genes:
        gse37302_col.append(1)
    else:
        gse37302_col.append(0)

    if gen in gse39683_genecounts1_genes:
        gse39683_genecounts1_col.append(1)
    else:
        gse39683_genecounts1_col.append(0)

    if gen in gse17306_genes:
        gse17306_col.append(1)
    else:
        gse17306_col.append(0)

    if gen in gse16558_gene:
        gse16558_col.append(1)
    else:
        gse16558_col.append(0)

    if gen in gse72213_genes:
        gse72213_col.append(1)
    else:
        gse72213_col.append(0)

    if gen in gse17498_genes:
        gse17498_col.append(1)
    else:
        gse17498_col.append(0)

    if gen in gse89182_genes:
        gse89182_col.append(1)
    else:
        gse89182_col.append(0)

    if gen in gse125363_genes:
        gse125363_col.append(1)
    else:
        gse125363_col.append(0)

    if gen in gse167042_genes:
        gse167042_col.append(1)
    else:
        gse167042_col.append(0)
        
    if gen in gse149833_genes:
        gse149833_col.append(1)
    else:
        gse149833_col.append(0)

    if gen in gse137369_genes:
        gse137369_col.append(1)
    else:
        gse137369_col.append(0)

df_dataset_counts['Genes'] = genelist
df_dataset_counts['Rank'] = generank
df_dataset_counts['GSE37302'] = gse37302_col
df_dataset_counts['GSE39683'] = gse39683_genecounts1_col
df_dataset_counts['GSE17306'] = gse17306_col
df_dataset_counts['GSE16558'] = gse16558_col
df_dataset_counts['GSE72213'] = gse72213_col
df_dataset_counts['GSE17498'] = gse17498_col
df_dataset_counts['GSE89182'] = gse89182_col
df_dataset_counts['GSE125363'] = gse125363_col
df_dataset_counts['GSE149833'] = gse149833_col
df_dataset_counts['GSE167042'] = gse167042_col
df_dataset_counts['GSE137369'] = gse137369_col
df_dataset_counts["Total_validated_datasets"] = [sum(df_dataset_counts.loc[idx,:].values.tolist()[2:]) for idx in range(df_dataset_counts.shape[0])]

df_dataset_counts.to_excel('gene798_dataset_counts.xlsx', index=False, encoding="utf=8")
df_dataset_counts.head()

 13%|█▎        | 107/798 [00:00<00:00, 1062.58it/s]

100%|██████████| 798/798 [00:00<00:00, 925.29it/s]

,Genes,Rank,GSE37302,GSE39683,GSE17306,GSE16558,GSE72213,GSE17498,GSE89182,GSE125363,GSE149833,GSE167042,GSE137369,Total_validated_datasets
0,MUC6,1,0,0,1,0,0,1,0,1,1,0,0,4
1,LILRA1,2,0,0,0,0,0,0,0,1,1,0,0,2
2,LILRB1,3,0,0,1,0,0,1,1,1,0,1,0,5
3,PDE4DIP,4,1,0,1,1,0,1,0,1,0,0,0,5
4,EIF4EBP1,5,1,0,1,0,0,1,1,1,0,1,0,6

In [20]:
df_dataset_counts = pd.DataFrame()
gse37302_col, gse39683_genecounts1_col, gse17306_col, gse16558_col, gse72213_col, gse17498_col, gse89182_col, gse125363_col, gse167042_col, gse149833_col, gse137369_col = [], [],[],[],[],[],[],[],[],[], []
generank = []
genelist = top500_genes
for gen in tqdm(genelist):
    generank.append(genelist.index(gen)+1)
    if gen in gse37302_genes:
        gse37302_col.append(1)
    else:
        gse37302_col.append(0)

    if gen in gse39683_genecounts1_genes:
        gse39683_genecounts1_col.append(1)
    else:
        gse39683_genecounts1_col.append(0)

    if gen in gse17306_genes:
        gse17306_col.append(1)
    else:
        gse17306_col.append(0)

    if gen in gse16558_gene:
        gse16558_col.append(1)
    else:
        gse16558_col.append(0)

    if gen in gse72213_genes:
        gse72213_col.append(1)
    else:
        gse72213_col.append(0)

    if gen in gse17498_genes:
        gse17498_col.append(1)
    else:
        gse17498_col.append(0)

    if gen in gse89182_genes:
        gse89182_col.append(1)
    else:
        gse89182_col.append(0)

    if gen in gse125363_genes:
        gse125363_col.append(1)
    else:
        gse125363_col.append(0)

    if gen in gse167042_genes:
        gse167042_col.append(1)
    else:
        gse167042_col.append(0)
        
    if gen in gse149833_genes:
        gse149833_col.append(1)
    else:
        gse149833_col.append(0)

    if gen in gse137369_genes:
        gse137369_col.append(1)
    else:
        gse137369_col.append(0)

df_dataset_counts['Genes'] = genelist
df_dataset_counts['Rank'] = generank
df_dataset_counts['GSE37302'] = gse37302_col
df_dataset_counts['GSE39683'] = gse39683_genecounts1_col
df_dataset_counts['GSE17306'] = gse17306_col
df_dataset_counts['GSE16558'] = gse16558_col
df_dataset_counts['GSE72213'] = gse72213_col
df_dataset_counts['GSE17498'] = gse17498_col
df_dataset_counts['GSE89182'] = gse89182_col
df_dataset_counts['GSE125363'] = gse125363_col
df_dataset_counts['GSE149833'] = gse149833_col
df_dataset_counts['GSE167042'] = gse167042_col
df_dataset_counts['GSE137369'] = gse137369_col
df_dataset_counts["Total_validated_datasets"] = [sum(df_dataset_counts.loc[idx,:].values.tolist()[2:]) for idx in range(df_dataset_counts.shape[0])]

df_dataset_counts.to_excel('top500_dataset_counts.xlsx', index=False, encoding="utf=8")
df_dataset_counts.head()

  0%|          | 0/500 [00:00<?, ?it/s]

100%|██████████| 500/500 [00:00<00:00, 918.57it/s]

,Genes,Rank,GSE37302,GSE39683,GSE17306,GSE16558,GSE72213,GSE17498,GSE89182,GSE125363,GSE149833,GSE167042,GSE137369,Total_validated_datasets
0,MUC6,1,0,0,1,0,0,1,0,1,1,0,0,4
1,LILRA1,2,0,0,0,0,0,0,0,1,1,0,0,2
2,LILRB1,3,0,0,1,0,0,1,1,1,0,1,0,5
3,PDE4DIP,4,1,0,1,1,0,1,0,1,0,0,0,5
4,EIF4EBP1,5,1,0,1,0,0,1,1,1,0,1,0,6

In [19]:
df_dataset_counts = pd.DataFrame()
gene701 = open("/home/vivek/jupyter_notebooks/bio_dgi_extension/final_compilation_work/gene701/gene701.txt").read().split("\n")
gene701 = [i for i in gene701 if i]
gse37302_col, gse39683_genecounts1_col, gse17306_col, gse16558_col, gse72213_col, gse17498_col, gse89182_col, gse125363_col, gse167042_col, gse149833_col, gse137369_col = [], [],[],[],[],[],[],[],[],[], []
generank = []
genelist = gene701
for gen in tqdm(genelist):
    generank.append(genelist.index(gen)+1)
    if gen in gse37302_genes:
        gse37302_col.append(1)
    else:
        gse37302_col.append(0)

    if gen in gse39683_genecounts1_genes:
        gse39683_genecounts1_col.append(1)
    else:
        gse39683_genecounts1_col.append(0)

    if gen in gse17306_genes:
        gse17306_col.append(1)
    else:
        gse17306_col.append(0)

    if gen in gse16558_gene:
        gse16558_col.append(1)
    else:
        gse16558_col.append(0)

    if gen in gse72213_genes:
        gse72213_col.append(1)
    else:
        gse72213_col.append(0)

    if gen in gse17498_genes:
        gse17498_col.append(1)
    else:
        gse17498_col.append(0)

    if gen in gse89182_genes:
        gse89182_col.append(1)
    else:
        gse89182_col.append(0)

    if gen in gse125363_genes:
        gse125363_col.append(1)
    else:
        gse125363_col.append(0)

    if gen in gse167042_genes:
        gse167042_col.append(1)
    else:
        gse167042_col.append(0)
        
    if gen in gse149833_genes:
        gse149833_col.append(1)
    else:
        gse149833_col.append(0)

    if gen in gse137369_genes:
        gse137369_col.append(1)
    else:
        gse137369_col.append(0)

df_dataset_counts['Genes'] = genelist
df_dataset_counts['Rank'] = generank
df_dataset_counts['GSE37302'] = gse37302_col
df_dataset_counts['GSE39683'] = gse39683_genecounts1_col
df_dataset_counts['GSE17306'] = gse17306_col
df_dataset_counts['GSE16558'] = gse16558_col
df_dataset_counts['GSE72213'] = gse72213_col
df_dataset_counts['GSE17498'] = gse17498_col
df_dataset_counts['GSE89182'] = gse89182_col
df_dataset_counts['GSE125363'] = gse125363_col
df_dataset_counts['GSE149833'] = gse149833_col
df_dataset_counts['GSE167042'] = gse167042_col
df_dataset_counts['GSE137369'] = gse137369_col
df_dataset_counts["Total_validated_datasets"] = [sum(df_dataset_counts.loc[idx,:].values.tolist()[2:]) for idx in range(df_dataset_counts.shape[0])]

df_dataset_counts.to_excel('/home/vivek/jupyter_notebooks/bio_dgi_extension/final_compilation_work/gene701/top701_dataset_counts.xlsx', index=False, encoding="utf=8")
df_dataset_counts.head()

  0%|          | 0/701 [00:00<?, ?it/s]

100%|██████████| 701/701 [00:00<00:00, 1009.12it/s]

,Genes,Rank,GSE37302,GSE39683,GSE17306,GSE16558,GSE72213,GSE17498,GSE89182,GSE125363,GSE149833,GSE167042,GSE137369,Total_validated_datasets
0,ABCA1,1,1,0,1,0,0,1,0,1,1,0,0,5
1,ABCA3,2,0,0,1,0,0,1,0,1,1,0,0,4
2,ABCA7,3,0,0,1,0,0,1,0,1,1,1,0,5
3,ABL2,4,0,0,1,0,0,1,0,1,0,0,0,3
4,ACACB,5,0,0,1,0,0,1,1,1,0,1,0,5