In [1]:
import pandas as pd
from tqdm import tqdm

In [14]:
driver_list1 = pd.read_csv('/home/vivek/driverGenes_Oncogene_TSG/IntOGen-DriverGenes_MM.tsv', sep = '\t', index_col = 0).index.tolist()
driver_list1 = [i.replace(' ','') for i in driver_list1]
driver_list1 = [i for i in driver_list1 if i]
driver_list2 = open('/home/vivek/driverGenes_Oncogene_TSG/list_of_63_driver_genes.txt').read().split('\n')
driver_list2 = [i.replace(' ','') for i in driver_list2]
driver_list2 = [i for i in driver_list2 if i]
driver_list3 = open('/home/vivek/driverGenes_Oncogene_TSG/Genomic_landscape_and_chronological_reconstruction_of_driver_events_in_multiple.txt').read().split('\n')
driver_list3 = [i.replace(' ','') for i in driver_list3]
driver_list3 = [i for i in driver_list3 if i]
driver_list4 = open("/home/vivek/driverGenes_Oncogene_TSG/driver_literature/heterogeneity_of_genomic_evolution_and_mutational_profiles_mm.txt").read().split('\n')
driver_list4 = [i.replace(' ','') for i in driver_list4]
driver_list4 = [i for i in driver_list4 if i]
driver_list5 = open("/home/vivek/driverGenes_Oncogene_TSG/driver_literature/revealing_impact_of_sv.txt").read().split('\n')
driver_list5 = [i.replace(' ','') for i in driver_list5]
driver_list5 = [i for i in driver_list5 if i]
driver_list6 = open("/home/vivek/driverGenes_Oncogene_TSG/driver_literature/role_of_aid.txt").read().split('\n')
driver_list6 = [i.replace(' ','') for i in driver_list6]
driver_list6 = [i for i in driver_list6 if i]
driver_list7 = open("/home/vivek/driverGenes_Oncogene_TSG/driver_literature/wgs_of_mm_reveals_oncogenic_pathways_are_targeted.txt").read().split('\n')
driver_list7 = [i.replace(' ','') for i in driver_list7]
driver_list7 = [i for i in driver_list7 if i]
driver_list = list(set(driver_list2 + driver_list3 + driver_list4 + driver_list5 + driver_list6 + driver_list7))

oncokb = pd.read_csv('/home/vivek/driverGenes_Oncogene_TSG/cancerGeneList.tsv', sep='\t', index_col=0)
oncokb_oncogenes = oncokb[oncokb['Is Oncogene'] == 'Yes'].index.tolist()
oncokb_tsg = oncokb[oncokb['Is Tumor Suppressor Gene'] == 'Yes'].index.tolist()
cosmic = pd.read_csv('/home/vivek/driverGenes_Oncogene_TSG/cosmic_v97/Cosmic_v97.csv', index_col=0, header=0)
cosmic_oncogene = [cosmic.index.tolist()[i] for i in range(cosmic.shape[0]) if 'oncogene' in str(cosmic.iloc[i,13])]
cosmic_tsg = [cosmic.index.tolist()[i] for i in range(cosmic.shape[0]) if 'TSG' in str(cosmic.iloc[i,13])]
oncogenes = list(set(oncokb_oncogenes + cosmic_oncogene))
tsg = list(set(oncokb_tsg + cosmic_tsg))
cosmic_actionable_gene1 = pd.read_excel('/home/vivek/driverGenes_Oncogene_TSG/LIST_OF_ACTIONABLE_GENE.xlsx').iloc[:,0].tolist()
target_actionable_gene1 = pd.read_excel('/home/vivek/driverGenes_Oncogene_TSG/TARGET_db_v3_02142015.xlsx')['Gene'].values.tolist()
all_ag = list(set(cosmic_actionable_gene1 + target_actionable_gene1))
all_prev = list(set(oncogenes + tsg + all_ag + driver_list))

all_imp_genes = pd.read_excel("/home/vivek/jupyter_notebooks/bio_dgi_extension/ppi_string_merged/new_model4/best_performing_model/all_imp_genes.xlsx", index_col=0)
gene28257 = open("/home/vivek/jupyter_notebooks/bio_dgi_extension/final_compilation_work/gene28257.txt").read().split('\n')
gene28257 = [i for i in gene28257 if i]

/home/vivek/.local/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [3]:
gene282_variant_profiles = pd.read_excel("/home/vivek/jupyter_notebooks/bio_dgi_extension/final_compilation_work/gene_filtered_detailed_analysis_snvs_cnvs_svs_lof_v7.xlsx", index_col=0)
gene282_variant_profiles = gene282_variant_profiles[["snv_criterion","cnv_criterion","sv_criterion","lof_criterion"]]
gene282_data = pd.read_excel("/home/vivek/jupyter_notebooks/bio_dgi_extension/final_compilation_work/survival_analysis/282_genepanel/gene282_additional_information2.xlsx", index_col=0)
gene282 = gene282_data["elements"].values.tolist()
gene572 = open("/home/vivek/jupyter_notebooks/bio_dgi_extension/final_compilation_work/gene625/gene_panel_572.txt", "r").read().split("\n")
gene572 = [i for i in gene572 if i]

In [15]:
cutler26 = open("/home/vivek/jupyter_notebooks/bio_dgi_extension/panel_comparison/cutler26.txt").read().split("\n")
cutler26 = [x for x in cutler26 if x != '']
bolli182 = open("/home/vivek/jupyter_notebooks/bio_dgi_extension/panel_comparison/bolli182.txt").read().split("\n")
bolli182 = [x for x in bolli182 if x != '']
kortum47 = open("/home/vivek/jupyter_notebooks/bio_dgi_extension/panel_comparison/kortum47.txt").read().split("\n")
kortum47 = [x for x in kortum47 if x != '']
sudha228 = open("/home/vivek/jupyter_notebooks/bio_dgi_extension/panel_comparison/sudha228.txt").read().split("\n")
sudha228 = [x for x in sudha228 if x != '']
white465 = open("/home/vivek/jupyter_notebooks/bio_dgi_extension/panel_comparison/white465.txt").read().split("\n")
white465 = [x for x in white465 if x != '']

In [16]:
df_common = pd.DataFrame(columns=["cutler26", "bolli182", "kortum47", "sudha228", "white465"])
df_common["cutler26"] = [[i for i in gene572 if i in cutler26].__len__()]
df_common["bolli182"] = [[i for i in gene572 if i in bolli182].__len__()]
df_common["kortum47"] = [[i for i in gene572 if i in kortum47].__len__()]
df_common["sudha228"] = [[i for i in gene572 if i in sudha228].__len__()]
df_common["white465"] = [[i for i in gene572 if i in white465].__len__()]
df_common

   cutler26  bolli182  kortum47  sudha228  white465
0        24       130        27       140       145

In [17]:
all_genes = sorted(list(set(cutler26 + bolli182 + kortum47 + sudha228 + white465 + gene572)))

In [18]:
# [k for k in gene282_variant_profiles.loc["KRAS"].to_dict() if gene282_variant_profiles.loc["KRAS"].to_dict()[k] == 1]

In [19]:
all_genes_df = pd.DataFrame()
whether_cutler26, whether_bolli182, whether_kortum47, whether_sudha228, whether_white465, whether_gene572 = [], [], [], [], [], []
gene_var_profile = []
for gen in tqdm(all_genes):
    if gen in cutler26:
        whether_cutler26.append(1)
    else:
        whether_cutler26.append(0)
        
    if gen in bolli182:
        whether_bolli182.append(1)
    else:
       whether_bolli182.append(0)
       
    if gen in kortum47:
        whether_kortum47.append(1)
    else:
        whether_kortum47.append(0)
        
    if gen in sudha228:
        whether_sudha228.append(1)
    else:
        whether_sudha228.append(0)
        
    if gen in white465:
        whether_white465.append(1)
    else:
        whether_white465.append(0)
        
    if gen in gene572:
        whether_gene572.append(1)
        # gene_var_profile.append([k for k in gene282_variant_profiles.loc[gen].to_dict() if gene282_variant_profiles.loc[gen].to_dict()[k] == 1])
    else:
        whether_gene572.append(0)
        # gene_var_profile.append(".")
        
all_genes_df["gene"] = all_genes
all_genes_df["kortum47"] = whether_kortum47
all_genes_df["bolli182"] = whether_bolli182
all_genes_df["white465"] = whether_white465
all_genes_df["cutler26"] = whether_cutler26
all_genes_df["sudha228"] = whether_sudha228
all_genes_df["gene572"] = whether_gene572
# all_genes_df["gene282_var_profile"] = gene_var_profile
all_genes_df.to_excel("/home/vivek/jupyter_notebooks/bio_dgi_extension/panel_comparison/all_genes.xlsx", index=False)
all_genes_df.head()

100%|██████████| 988/988 [00:00<00:00, 48098.48it/s]

    gene  kortum47  bolli182  white465  cutler26  sudha228  gene572
0   AASS         0         0         1         0         0        0
1  ABCA1         0         0         0         0         0        1
2  ABCA2         0         0         1         0         0        0
3  ABCA3         0         0         0         0         0        1
4  ABCA7         0         0         0         0         0        1

In [20]:
prev_panel_genes = pd.DataFrame()

num_og, num_tsg, num_odg, num_dg, num_ag  = [], [], [], [], []

num_og = [[i for i in kortum47 if i in oncogenes].__len__(), 
          [i for i in bolli182 if i in oncogenes].__len__(), 
          [i for i in white465 if i in oncogenes].__len__(),
          [i for i in cutler26 if i in oncogenes].__len__(),
          [i for i in sudha228 if i in oncogenes].__len__(),
          [i for i in gene572 if i in oncogenes].__len__(),
          ]

num_tsg = [[i for i in kortum47 if i in tsg].__len__(), 
          [i for i in bolli182 if i in tsg].__len__(), 
          [i for i in white465 if i in tsg].__len__(),
          [i for i in cutler26 if i in tsg].__len__(),
          [i for i in sudha228 if i in tsg].__len__(),
          [i for i in gene572 if i in tsg].__len__(),
          ]

num_odg = [[i for i in kortum47 if i in oncogenes and i in driver_list].__len__(), 
          [i for i in bolli182 if i in oncogenes and i in driver_list].__len__(), 
          [i for i in white465 if i in oncogenes and i in driver_list].__len__(),
          [i for i in cutler26 if i in oncogenes and i in driver_list].__len__(),
          [i for i in sudha228 if i in oncogenes and i in driver_list].__len__(),
          [i for i in gene572 if i in oncogenes and i in driver_list].__len__(),
          ]

num_dg = [[i for i in kortum47 if i in driver_list].__len__(), 
          [i for i in bolli182 if i in driver_list].__len__(), 
          [i for i in white465 if i in driver_list].__len__(),
          [i for i in cutler26 if i in driver_list].__len__(),
          [i for i in sudha228 if i in driver_list].__len__(),
          [i for i in gene572 if i in driver_list].__len__(),
          ]

num_odg1 = [[i for i in kortum47 if i in oncogenes and i in driver_list1].__len__(), 
          [i for i in bolli182 if i in oncogenes and i in driver_list1].__len__(), 
          [i for i in white465 if i in oncogenes and i in driver_list1].__len__(),
          [i for i in cutler26 if i in oncogenes and i in driver_list1].__len__(),
          [i for i in sudha228 if i in oncogenes and i in driver_list1].__len__(),
          [i for i in gene572 if i in oncogenes and i in driver_list1].__len__(),
          ]

num_dg1 = [[i for i in kortum47 if i in driver_list1].__len__(), 
          [i for i in bolli182 if i in driver_list1].__len__(), 
          [i for i in white465 if i in driver_list1].__len__(),
          [i for i in cutler26 if i in driver_list1].__len__(),
          [i for i in sudha228 if i in driver_list1].__len__(),
          [i for i in gene572 if i in driver_list1].__len__(),
          ]

num_ag = [[i for i in kortum47 if i in all_ag].__len__(), 
          [i for i in bolli182 if i in all_ag].__len__(), 
          [i for i in white465 if i in all_ag].__len__(),
          [i for i in cutler26 if i in all_ag].__len__(),
          [i for i in sudha228 if i in all_ag].__len__(),
          [i for i in gene572 if i in all_ag].__len__(),
          ]

panel_lists = ["kortum47","bolli182","white465","cutler26",'sudha228','gene572']
total_genes = [47,182,465,26,228,572]

prev_panel_genes["panel"] = panel_lists
prev_panel_genes["total_genes"] = total_genes
prev_panel_genes["num_og"] = num_og
prev_panel_genes["num_tsg"] = num_tsg
prev_panel_genes["num_odg_intogen"] = num_odg1
prev_panel_genes["num_odg"] = num_odg
prev_panel_genes["num_dg_intogen"] = num_dg1
prev_panel_genes["num_dg"] = num_dg
prev_panel_genes["num_ag"] = num_ag
prev_panel_genes.to_excel("/home/vivek/jupyter_notebooks/bio_dgi_extension/panel_comparison/prev_panel_genes.xlsx", index=False)
prev_panel_genes

,panel,total_genes,num_og,num_tsg,num_odg_intogen,num_odg,num_dg_intogen,num_dg,num_ag
0,kortum47,47,9,17,7,7,18,20,8
1,bolli182,182,58,85,9,14,21,43,65
2,white465,465,52,65,13,18,32,58,54
3,cutler26,26,10,15,8,8,18,22,11
4,sudha228,228,68,87,15,27,35,87,61
5,gene572,572,125,146,17,27,40,74,105